version: "3"

services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        ports:
            - '8080:443'
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        links:
            - php

    php:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS PORT=6379"
            - "REDIS_HOST=redis"
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli/Dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS PORT=6379"
            - "REDIS_HOST=redis"
    mysql:
        image: mariadb
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - '33061:3306'
    node:
        build:
            context: ./
            dockerfile: docker/node/Dockerfile
        volumes:
            - ./:/var/www
        tty: true

    redis:
        image: redis
        ports:
            - "63791:6379"
